QuintaApp/QuintaApp/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuintaApp.Models
{
    public class Funcionario
    {
        public ushort FuncId { get; set; }
        public string FuncNome { get; set; }
        public string FuncFuncao { get; set; }
    }
}

QuintaApp/QuintaApp/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompareAttribute = System.ComponentModel.DataAnnotations.CompareAttribute;

namespace QuintaApp.Models
{
    public class Usuario
    {
        //Como o id não é preenchido, ele é considerado 0
        [Range(1,200,ErrorMessage ="O Id deve ser entre 1 e 200")]
        public int UsuId { get; set; }

        [Display(Name ="Nome")]
        [Required (ErrorMessage ="O nome deve ser preenchido")]
        public string UsuNome { get; set; }

        [Display(Name = "Observação")]
        [StringLength(50,MinimumLength =5, ErrorMessage ="O campo deve ter entre 5 e 50 caracteres")]
        public string UsuObs { get; set; }

        [Display(Name = "Data de nascimento")]
        [Required(ErrorMessage = "A data deve ser preenchida")]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}", ApplyFormatInEditMode =true)]
        public DateTime UsuNasc { get; set; }

        [Display(Name = "E-mail")]
        [RegularExpression(@"^[a-zA-Z] + (([\'\,\.\-][a-zA-Z])?[a-zA-Z]*)*\s+<(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})>$|^(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})$", ErrorMessage ="Digite um e-mail válido")]
        public string UsuEmail { get; set; }

        [Display(Name = "Login")]
        [Remote ("ValidaLogin", "Usuario", ErrorMessage ="Este login já existe")]
        [RegularExpression(@"[a-zA-Z]{5,15}", ErrorMessage = "Somente letras, entre 5 e 15 caracteres")]
        [Required(ErrorMessage = "O login é obrigatório")]
        public string UsuLogin { get; set; }

        [Display(Name = "Senha")]
        [Required(ErrorMessage = "A senha é obrigatória")]
        public string UsuSenha { get; set; }

        [Display(Name = "Confirme a senha")]
        [Compare("UsuSenha", ErrorMessage ="As senhas são diferentes")]
        public string UsuConfirmaSenha { get; set; }
    }
}

QuintaApp/QuintaApp/Controllers/FuncionarioController.cs
using QuintaApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuintaApp.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Index()
        {
            Funcionario func = new Funcionario()
            {
                FuncId = 1,
                FuncNome = "Bronquinho",
                FuncFuncao = "Folião"
            };
            return View(func);
        }

        //[HttpPost]
        //public ActionResult Listar(ushort FuncId, string FuncNome, string FuncFuncao) - os parâmetros têm o mesmo nome dado aos campos no form
        //{
        //    ViewData["FuncId"] = FuncId;
        //    ViewData["FuncNome"] = FuncNome;
        //    ViewData["FuncFuncao"] =FuncFuncao;
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Listar(FormCollection form)
        //{
        //    ViewData["FuncId"] = form["FuncId"];
        //    ViewData["FuncNome"] = form["FuncNome"];
        //    ViewData["FuncFuncao"] = form["FuncFuncao"];
        //    return View();
        //}

        [HttpPost]
        public ActionResult Listar(Funcionario func)
        {
            //ViewData["FuncId"] = func.FuncId;
            //ViewData["FuncNome"] = func.FuncNome;
            //ViewData["FuncFuncao"] = func.FuncFuncao;
            return View(func);
        }
    }
}

QuintaApp/QuintaApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuintaApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

QuintaApp/QuintaApp/Controllers/UsuarioController.cs
using QuintaApp.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuintaApp.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            var usuario = new Usuario();

            return View(usuario);
        }

        [HttpPost]
        public ActionResult Index(Usuario usuario)
        {
            // validação de um único item:
            //if (string.IsNullOrEmpty(usuario.UsuNome))
            //{
            //    ModelState.AddModelError("UsuNome", "O campo nome é obrigatório");
            //}
            //if (usuario.UsuSenha != usuario.UsuConfirmaSenha)
            //{
            //    ModelState.AddModelError("", "As senhas são diferentes");
            //}

            if (ModelState.IsValid)
            {            
                return View("Resultado", usuario);
            }
            return View(usuario);
        }

        public ActionResult Resultado(Usuario usuario)
        {
            return View(usuario);
        }

        public ActionResult ValidaLogin(string UsuLogin)
        {
            var dbExemplo = new Collection<string>
            {
                "Adriana",
                "Amanda",
                "Alberto"
            };
            return Json(dbExemplo.All(a => a.ToLower() != UsuLogin.ToLower()),JsonRequestBehavior.AllowGet);
        }
    }
}

QuintaApp/QuintaApp/Views/Funcionario/Index.cshtml
@model QuintaApp.Models.Funcionario

@{
    ViewBag.Title = "Index";
}

<h2>Funcionário</h2>

@*<form action="~/Funcionario/Listar" method="post">*@

@using (Html.BeginForm("Listar", "Funcionario", FormMethod.Post))
{
    <fieldset>
        <legend>Dados de funcionário</legend>
    </fieldset>
    <div>
        <label for="FuncId">Código</label>
    </div>
    <div>
        @*<input type="number" value="@Model.FuncId" name="FuncId" />*@
        @Html.EditorFor(x => x.FuncId)
    </div>
    <br />

    <div>
        <label for="FuncNome">Nome</label>
    </div>
    <div>
        <input type="text" value="@Model.FuncNome" name="FuncNome" />
    </div>
    <br />

    <div>
        <label for="FuncFuncao">Função</label>
    </div>
    <div>
        <input type="text" value="@Model.FuncFuncao" name="FuncFuncao" />
    </div>
    <br />

    <input type="submit" value="Enviar" />
}
@*</form>*@

QuintaApp/QuintaApp/Views/Funcionario/Listar.cshtml
@model QuintaApp.Models.Funcionario
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<div>
    <b>Id do funcionário:</b>
</div>
<div>
    @Model.FuncId
</div>

<div>
    <b>Nome do funcionário:</b>
</div>
<div>
    @Model.FuncNome
</div>

<div>
    <b>Função do funcionário:</b>
</div>
<div>
    @Model.FuncFuncao
</div>

<br />
@*<a href="~/">Voltar</a>*@

@Html.ActionLink("Voltar", "Index", "Home")

QuintaApp/QuintaApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

QuintaApp/QuintaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quinta App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Funcionário", "Index", "Funcionario")</li>
                    <li>@Html.ActionLink("Usuário", "Index", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QuintaApp/QuintaApp/Views/Usuario/Index.cshtml
@model QuintaApp.Models.Usuario

@{
    ViewBag.Title = "Index";
}

<h2>Validação de Usuário</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true);
<fieldset>
    <legend>Dados do usuário</legend>
    <div class="editor-label">
        @Html.LabelFor(m => m.UsuId)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.UsuId)
        @Html.ValidationMessageFor(m => m.UsuId, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuNome)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.UsuNome)
        @Html.ValidationMessageFor(m => m.UsuNome, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuObs)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(m => m.UsuObs)
        @Html.ValidationMessageFor(m => m.UsuObs, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuNasc)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.UsuNasc)
        @Html.ValidationMessageFor(m => m.UsuNasc, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuEmail)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.UsuEmail)
        @Html.ValidationMessageFor(m => m.UsuEmail, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuLogin)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.UsuLogin)
        @Html.ValidationMessageFor(m => m.UsuLogin, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuSenha)
    </div>
    <div class="editor-field">
        @Html.PasswordFor(m => m.UsuSenha)
        @Html.ValidationMessageFor(m => m.UsuSenha, "", new { @class = "text-danger" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.UsuConfirmaSenha)
    </div>
    <div class="editor-field">
        @Html.PasswordFor(m => m.UsuConfirmaSenha)
        @Html.ValidationMessageFor(m => m.UsuConfirmaSenha, "", new { @class = "text-danger" })
    </div>
    <br />

    <p><input type="submit" value="Cadastrar" /></p>

</fieldset>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

}

QuintaApp/QuintaApp/Views/Usuario/Resultado.cshtml
@model QuintaApp.Models.Usuario

@{
    ViewBag.Title = "Resultado";
}

<h2>Listar usuário</h2>

<fieldset>
    <legend>Usuário cadastrado</legend>

    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuId)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuId)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuNome)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuNome)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuObs)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuObs)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuNasc)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuNasc)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuEmail)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuEmail)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuLogin)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuLogin)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuSenha)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuSenha)
    </div>
    <br />
    <div class="editor-label">
        @Html.DisplayNameFor(m => m.UsuConfirmaSenha)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.UsuConfirmaSenha)
    </div>
    <br />
    <p>@Html.ActionLink("Voltar", "Index")</p>
</fieldset>